// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11RrUh0-CGqEAumiZl_cspnZ28nyZZb4',
    appId: '1:912909461876:web:b15b3e752bddf31f82a421',
    messagingSenderId: '912909461876',
    projectId: 'tessst-2aafc',
    authDomain: 'tessst-2aafc.firebaseapp.com',
    storageBucket: 'tessst-2aafc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB24BzpR7I9C2-PTnyDu3IjKIP8dd84KxM',
    appId: '1:912909461876:android:47275ec3b8451ae882a421',
    messagingSenderId: '912909461876',
    projectId: 'tessst-2aafc',
    storageBucket: 'tessst-2aafc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCHRdhj44eI0dcqjYjaEQXFLC7jAr7D0',
    appId: '1:912909461876:ios:1af96570422f3de582a421',
    messagingSenderId: '912909461876',
    projectId: 'tessst-2aafc',
    storageBucket: 'tessst-2aafc.appspot.com',
    iosBundleId: 'com.example.tests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCHRdhj44eI0dcqjYjaEQXFLC7jAr7D0',
    appId: '1:912909461876:ios:1af96570422f3de582a421',
    messagingSenderId: '912909461876',
    projectId: 'tessst-2aafc',
    storageBucket: 'tessst-2aafc.appspot.com',
    iosBundleId: 'com.example.tests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA11RrUh0-CGqEAumiZl_cspnZ28nyZZb4',
    appId: '1:912909461876:web:0a91b3472f837fea82a421',
    messagingSenderId: '912909461876',
    projectId: 'tessst-2aafc',
    authDomain: 'tessst-2aafc.firebaseapp.com',
    storageBucket: 'tessst-2aafc.appspot.com',
  );
}
